site_name: Suhail Mulla | Aziraphail
site_url: https://aziraphail.github.io/

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    # - navigation.prune # Not compatible with navigation.expand
    # - navigation.indexes # Not compatible with  toc.integrate
    - navigation.top

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Projects: Projects/index.md
  - Resume: Resume/Resume.md
  - Certifications: Certifications/Certifications.md

markdown_extensions:
  - neoteroi.cards

extra_css:
  - stylesheets/neoteroi-mkdocs.css
